server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://47.103.194.103:3306/joinintern_dev
    username: dev
    password: join@intern
    schema:
      - classpath:sql/dev-db.sql
      - classpath:sql/ddl.sql
      - classpath:sql/common-data.sql
      - classpath:sql/dev-data.sql
