server:
  port: 443
  ssl:
    key-store: classpath:3388229_joinintern.cn.pfx
    key-store-password: Q3pFv7Tj
#  error:
#    path: /index.html

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/joinintern
    username: prod
    password: join@intern
#  resources:
#    static-locations: /root/joinintern/public/
