server:
  port: 443
  ssl:
    key-store: classpath:3388229_joinintern.cn.pfx
    key-store-password: Q3pFv7Tj

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/joinintern
    username: prod
    password: join@intern
    schema:
      - classpath:sql/prod-db.sql
      - classpath:sql/ddl.sql
      - classpath:sql/common-data.sql
