spring:
  profiles:
    active: dev
  resources:
    static-locations:
      - file:/root/joinintern/public/
      - file:/root/joinintern/
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 30MB

joinintern:
  maxChunkLength: 4096
  maxChatBufferLen: 2048
  basePath: /root/joinintern/
