spring:
  profiles:
    active: dev
  resources:
    static-locations:
      - file:/root/joinintern/public/
      - file:/root/joinintern/media/

joinintern:
  maxChunkLength: 4096
  maxChatBufferLen: 2048
